version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  product-api:
    build: ./product-api
    container_name: product-api
    ports:
      - "8080:8080"
    environment:
      - "JAVA_OPTS=-Dnewrelic.config.app_name=v1/product-api -Dnewrelic.config.license_key= -Dspring.data.mongodb.uri=mongodb://local:local@mongo:27017/local?authSource=admin"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: local
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
      MONGO_NON_ROOT_USERNAM: local
      MONGO_NON_ROOT_PASSWORD: local
    command: ["--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db

